var owl = $('.owl-carousel');
owl.owlCarousel({
    items:1.6,
    loop:true,
    margin:0,
    mouseDrag:true,
    touchDrag:true,
    autoplay:true,
    dots:false,
    center:true,
    autoplayTimeout:5000,
    autoplayHoverPause:true
});
$('.play').on('click',function(){
    owl.trigger('play.owl.autoplay',[1000])
})
$('.stop').on('click',function(){
    owl.trigger('stop.owl.autoplay')
})